import type { Location, Property } from '@/types'

export const MOCK_LOCATIONS: Location[] = [
  { id: 'loc-1', name: 'Stockholm', type: 'stad', coordinates: { latitude: 59.3293, longitude: 18.0686 } },
  { id: 'loc-2', name: 'Södermalm', type: 'stadsdel', parentName: 'Stockholm', coordinates: { latitude: 59.3150, longitude: 18.0710 } },
  { id: 'loc-3', name: 'Vasastan', type: 'stadsdel', parentName: 'Stockholm', coordinates: { latitude: 59.3450, longitude: 18.0500 } },
  { id: 'loc-4', name: 'Östermalm', type: 'stadsdel', parentName: 'Stockholm', coordinates: { latitude: 59.3380, longitude: 18.0830 } },
  { id: 'loc-5', name: 'Kungsholmen', type: 'stadsdel', parentName: 'Stockholm', coordinates: { latitude: 59.3320, longitude: 18.0290 } },
  { id: 'loc-6', name: 'Gothenburg', type: 'stad', coordinates: { latitude: 57.7089, longitude: 11.9746 } },
  { id: 'loc-7', name: 'Linné', type: 'stadsdel', parentName: 'Gothenburg', coordinates: { latitude: 57.6960, longitude: 11.9540 } },
  { id: 'loc-8', name: 'Malmö', type: 'stad', coordinates: { latitude: 55.6050, longitude: 13.0038 } },
  { id: 'loc-9', name: 'Uppsala', type: 'stad', coordinates: { latitude: 59.8586, longitude: 17.6389 } },
  { id: 'loc-10', name: 'Solna', type: 'kommun', parentName: 'Stockholm', coordinates: { latitude: 59.3600, longitude: 18.0000 } },
]

const today = new Date().toISOString().split('T')[0]

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1', booliId: 100001, address: 'Hornsgatan 42', area: 'Södermalm', municipality: 'Stockholm',
    price: 4_950_000, pricePerSqm: 82_500, livingArea: 60, rooms: 2, floor: 4, totalFloors: 6,
    constructionYear: 1925, monthlyFee: 3_200, propertyType: 'apartment',
    coordinates: { latitude: 59.3171, longitude: 18.0494 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Charming two-room apartment in the heart of Södermalm with original details.',
    url: 'https://www.booli.se/annons/100001', publishedAt: today, daysOnMarket: 5,
  },
  {
    id: '2', booliId: 100002, address: 'Odengatan 18', area: 'Vasastan', municipality: 'Stockholm',
    price: 6_800_000, pricePerSqm: 85_000, livingArea: 80, rooms: 3, floor: 3, totalFloors: 5,
    constructionYear: 1912, monthlyFee: 4_100, propertyType: 'apartment',
    coordinates: { latitude: 59.3430, longitude: 18.0520 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Spacious three-room apartment on Odengatan with high ceilings and a balcony.',
    url: 'https://www.booli.se/annons/100002', publishedAt: today, daysOnMarket: 12,
  },
  {
    id: '3', booliId: 100003, address: 'Strandvägen 7', area: 'Östermalm', municipality: 'Stockholm',
    price: 14_500_000, pricePerSqm: 120_833, livingArea: 120, rooms: 4, floor: 5, totalFloors: 7,
    constructionYear: 1897, monthlyFee: 7_800, propertyType: 'apartment',
    coordinates: { latitude: 59.3310, longitude: 18.0830 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Prestigious apartment on Strandvägen with stunning water views.',
    url: 'https://www.booli.se/annons/100003', publishedAt: today, daysOnMarket: 21,
  },
  {
    id: '4', booliId: 100004, address: 'Fleminggatan 56', area: 'Kungsholmen', municipality: 'Stockholm',
    price: 3_750_000, pricePerSqm: 75_000, livingArea: 50, rooms: 2, floor: 2, totalFloors: 4,
    constructionYear: 1938, monthlyFee: 2_900, propertyType: 'apartment',
    coordinates: { latitude: 59.3340, longitude: 18.0340 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Bright two-room apartment on Kungsholmen, close to Rådhuset metro.',
    url: 'https://www.booli.se/annons/100004', publishedAt: today, daysOnMarket: 3,
  },
  {
    id: '5', booliId: 100005, address: 'Götgatan 31', area: 'Södermalm', municipality: 'Stockholm',
    price: 3_200_000, pricePerSqm: 80_000, livingArea: 40, rooms: 1, floor: 1, totalFloors: 5,
    constructionYear: 1905, monthlyFee: 2_400, propertyType: 'apartment',
    coordinates: { latitude: 59.3140, longitude: 18.0730 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Cozy one-room apartment steps from Medborgarplatsen.',
    url: 'https://www.booli.se/annons/100005', publishedAt: today, daysOnMarket: 8,
  },
  {
    id: '6', booliId: 100006, address: 'Norr Mälarstrand 20', area: 'Kungsholmen', municipality: 'Stockholm',
    price: 8_900_000, pricePerSqm: 89_000, livingArea: 100, rooms: 4, floor: 6, totalFloors: 6,
    constructionYear: 1945, monthlyFee: 5_200, propertyType: 'apartment',
    coordinates: { latitude: 59.3290, longitude: 18.0220 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Penthouse apartment with panoramic lake views on Norr Mälarstrand.',
    url: 'https://www.booli.se/annons/100006', publishedAt: today, daysOnMarket: 14,
  },
  {
    id: '7', booliId: 100007, address: 'Karlaplan 4', area: 'Östermalm', municipality: 'Stockholm',
    price: 5_600_000, pricePerSqm: 93_333, livingArea: 60, rooms: 2, floor: 3, totalFloors: 5,
    constructionYear: 1910, monthlyFee: 3_800, propertyType: 'apartment',
    coordinates: { latitude: 59.3390, longitude: 18.0860 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Elegant apartment at Karlaplan with period features.',
    url: 'https://www.booli.se/annons/100007', publishedAt: today, daysOnMarket: 6,
  },
  {
    id: '8', booliId: 100008, address: 'Sveavägen 112', area: 'Vasastan', municipality: 'Stockholm',
    price: 2_950_000, pricePerSqm: 73_750, livingArea: 40, rooms: 1, floor: 2, totalFloors: 4,
    constructionYear: 1930, monthlyFee: 2_100, propertyType: 'apartment',
    coordinates: { latitude: 59.3480, longitude: 18.0570 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Well-maintained studio apartment in central Vasastan.',
    url: 'https://www.booli.se/annons/100008', publishedAt: today, daysOnMarket: 19,
  },
  {
    id: '9', booliId: 100009, address: 'Ringvägen 85', area: 'Södermalm', municipality: 'Stockholm',
    price: 5_200_000, pricePerSqm: 74_286, livingArea: 70, rooms: 3, floor: 5, totalFloors: 6,
    constructionYear: 1955, monthlyFee: 3_600, propertyType: 'apartment',
    coordinates: { latitude: 59.3090, longitude: 18.0690 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Family-friendly three-room apartment with views over Tantolunden.',
    url: 'https://www.booli.se/annons/100009', publishedAt: today, daysOnMarket: 7,
  },
  {
    id: '10', booliId: 100010, address: 'Valhallavägen 150', area: 'Östermalm', municipality: 'Stockholm',
    price: 7_400_000, pricePerSqm: 82_222, livingArea: 90, rooms: 3, floor: 4, totalFloors: 5,
    constructionYear: 1935, monthlyFee: 4_800, propertyType: 'apartment',
    coordinates: { latitude: 59.3430, longitude: 18.0950 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Renovated apartment near Stadion with open floor plan.',
    url: 'https://www.booli.se/annons/100010', publishedAt: today, daysOnMarket: 10,
  },
  // Gothenburg
  {
    id: '11', booliId: 100011, address: 'Linnégatan 22', area: 'Linné', municipality: 'Gothenburg',
    price: 3_100_000, pricePerSqm: 62_000, livingArea: 50, rooms: 2, floor: 3, totalFloors: 4,
    constructionYear: 1920, monthlyFee: 2_800, propertyType: 'apartment',
    coordinates: { latitude: 57.6960, longitude: 11.9580 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Classic apartment in the popular Linné district.',
    url: 'https://www.booli.se/annons/100011', publishedAt: today, daysOnMarket: 4,
  },
  {
    id: '12', booliId: 100012, address: 'Vasagatan 38', area: 'Vasastan', municipality: 'Gothenburg',
    price: 2_450_000, pricePerSqm: 61_250, livingArea: 40, rooms: 1, floor: 2, totalFloors: 5,
    constructionYear: 1915, monthlyFee: 2_200, propertyType: 'apartment',
    coordinates: { latitude: 57.7020, longitude: 11.9640 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Compact one-room apartment in central Gothenburg.',
    url: 'https://www.booli.se/annons/100012', publishedAt: today, daysOnMarket: 15,
  },
  {
    id: '13', booliId: 100013, address: 'Haga Nygata 12', area: 'Haga', municipality: 'Gothenburg',
    price: 4_200_000, pricePerSqm: 70_000, livingArea: 60, rooms: 2, floor: 1, totalFloors: 3,
    constructionYear: 1880, monthlyFee: 3_100, propertyType: 'apartment',
    coordinates: { latitude: 57.6990, longitude: 11.9500 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Unique apartment in historic Haga with exposed brick.',
    url: 'https://www.booli.se/annons/100013', publishedAt: today, daysOnMarket: 9,
  },
  {
    id: '14', booliId: 100014, address: 'Eriksberg 5', area: 'Eriksberg', municipality: 'Gothenburg',
    price: 5_800_000, pricePerSqm: 72_500, livingArea: 80, rooms: 3, floor: 4, totalFloors: 8,
    constructionYear: 2005, monthlyFee: 4_500, propertyType: 'apartment',
    coordinates: { latitude: 57.7010, longitude: 11.9230 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Modern waterfront apartment in Eriksberg with harbor views.',
    url: 'https://www.booli.se/annons/100014', publishedAt: today, daysOnMarket: 11,
  },
  {
    id: '15', booliId: 100015, address: 'Kungsportsavenyen 34', area: 'Centrum', municipality: 'Gothenburg',
    price: 6_500_000, pricePerSqm: 81_250, livingArea: 80, rooms: 3, floor: 5, totalFloors: 6,
    constructionYear: 1900, monthlyFee: 4_200, propertyType: 'apartment',
    coordinates: { latitude: 57.7000, longitude: 11.9720 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Grand apartment on the famous Avenue in Gothenburg.',
    url: 'https://www.booli.se/annons/100015', publishedAt: today, daysOnMarket: 18,
  },
  // Malmö
  {
    id: '16', booliId: 100016, address: 'Möllevångsgatan 8', area: 'Möllevången', municipality: 'Malmö',
    price: 1_850_000, pricePerSqm: 46_250, livingArea: 40, rooms: 1, floor: 2, totalFloors: 4,
    constructionYear: 1928, monthlyFee: 2_100, propertyType: 'apartment',
    coordinates: { latitude: 55.5890, longitude: 13.0060 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Affordable one-room in vibrant Möllevången.',
    url: 'https://www.booli.se/annons/100016', publishedAt: today, daysOnMarket: 2,
  },
  {
    id: '17', booliId: 100017, address: 'Västra Hamnen 15', area: 'Västra Hamnen', municipality: 'Malmö',
    price: 4_300_000, pricePerSqm: 71_667, livingArea: 60, rooms: 2, floor: 7, totalFloors: 12,
    constructionYear: 2010, monthlyFee: 3_800, propertyType: 'apartment',
    coordinates: { latitude: 55.6130, longitude: 12.9790 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Modern apartment in Västra Hamnen with sea views.',
    url: 'https://www.booli.se/annons/100017', publishedAt: today, daysOnMarket: 13,
  },
  {
    id: '18', booliId: 100018, address: 'Regementsgatan 22', area: 'Davidshall', municipality: 'Malmö',
    price: 3_600_000, pricePerSqm: 60_000, livingArea: 60, rooms: 2, floor: 3, totalFloors: 5,
    constructionYear: 1935, monthlyFee: 2_900, propertyType: 'apartment',
    coordinates: { latitude: 55.5960, longitude: 12.9930 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Well-located apartment in the sought-after Davidshall area.',
    url: 'https://www.booli.se/annons/100018', publishedAt: today, daysOnMarket: 6,
  },
  // Houses
  {
    id: '19', booliId: 100019, address: 'Björkvägen 14', area: 'Bromma', municipality: 'Stockholm',
    price: 9_500_000, pricePerSqm: 63_333, livingArea: 150, rooms: 5, constructionYear: 1965,
    propertyType: 'house',
    coordinates: { latitude: 59.3380, longitude: 17.9400 },
    images: [{ url: '/placeholder-house.jpg' }],
    description: 'Family villa in Bromma with large garden.',
    url: 'https://www.booli.se/annons/100019', publishedAt: today, daysOnMarket: 20,
  },
  {
    id: '20', booliId: 100020, address: 'Ekvägen 7', area: 'Enskede', municipality: 'Stockholm',
    price: 7_200_000, pricePerSqm: 60_000, livingArea: 120, rooms: 4, constructionYear: 1948,
    propertyType: 'house',
    coordinates: { latitude: 59.2830, longitude: 18.0720 },
    images: [{ url: '/placeholder-house.jpg' }],
    description: 'Classic Enskede house with mature garden.',
    url: 'https://www.booli.se/annons/100020', publishedAt: today, daysOnMarket: 16,
  },
  {
    id: '21', booliId: 100021, address: 'Sjövägen 3', area: 'Hovås', municipality: 'Gothenburg',
    price: 12_800_000, pricePerSqm: 64_000, livingArea: 200, rooms: 6, constructionYear: 1990,
    propertyType: 'house',
    coordinates: { latitude: 57.6250, longitude: 11.9290 },
    images: [{ url: '/placeholder-house.jpg' }],
    description: 'Seaside villa in exclusive Hovås.',
    url: 'https://www.booli.se/annons/100021', publishedAt: today, daysOnMarket: 25,
  },
  // Townhouses
  {
    id: '22', booliId: 100022, address: 'Radhusvägen 9', area: 'Hägersten', municipality: 'Stockholm',
    price: 5_900_000, pricePerSqm: 59_000, livingArea: 100, rooms: 4, floor: 1, totalFloors: 2,
    constructionYear: 1975, monthlyFee: 2_800, propertyType: 'townhouse',
    coordinates: { latitude: 59.2960, longitude: 18.0100 },
    images: [{ url: '/placeholder-townhouse.jpg' }],
    description: 'Spacious townhouse in Hägersten with private patio.',
    url: 'https://www.booli.se/annons/100022', publishedAt: today, daysOnMarket: 7,
  },
  {
    id: '23', booliId: 100023, address: 'Kedjehusvägen 5', area: 'Täby', municipality: 'Stockholm',
    price: 6_400_000, pricePerSqm: 53_333, livingArea: 120, rooms: 5, floor: 1, totalFloors: 2,
    constructionYear: 1985, monthlyFee: 1_900, propertyType: 'townhouse',
    coordinates: { latitude: 59.4330, longitude: 18.0700 },
    images: [{ url: '/placeholder-townhouse.jpg' }],
    description: 'Well-maintained townhouse in family-friendly Täby.',
    url: 'https://www.booli.se/annons/100023', publishedAt: today, daysOnMarket: 11,
  },
  // More Stockholm apartments
  {
    id: '24', booliId: 100024, address: 'Drottninggatan 65', area: 'Norrmalm', municipality: 'Stockholm',
    price: 4_100_000, pricePerSqm: 91_111, livingArea: 45, rooms: 2, floor: 4, totalFloors: 6,
    constructionYear: 1890, monthlyFee: 3_400, propertyType: 'apartment',
    coordinates: { latitude: 59.3370, longitude: 18.0640 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Central apartment on Drottninggatan with great location.',
    url: 'https://www.booli.se/annons/100024', publishedAt: today, daysOnMarket: 4,
  },
  {
    id: '25', booliId: 100025, address: 'Birger Jarlsgatan 90', area: 'Östermalm', municipality: 'Stockholm',
    price: 9_200_000, pricePerSqm: 92_000, livingArea: 100, rooms: 4, floor: 2, totalFloors: 5,
    constructionYear: 1908, monthlyFee: 6_200, propertyType: 'apartment',
    coordinates: { latitude: 59.3430, longitude: 18.0790 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Magnificent four-room apartment with classic Östermalm charm.',
    url: 'https://www.booli.se/annons/100025', publishedAt: today, daysOnMarket: 15,
  },
  {
    id: '26', booliId: 100026, address: 'Folkungagatan 120', area: 'Södermalm', municipality: 'Stockholm',
    price: 3_800_000, pricePerSqm: 69_091, livingArea: 55, rooms: 2, floor: 1, totalFloors: 4,
    constructionYear: 1940, monthlyFee: 2_700, propertyType: 'apartment',
    coordinates: { latitude: 59.3130, longitude: 18.0830 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Ground floor apartment with access to courtyard garden.',
    url: 'https://www.booli.se/annons/100026', publishedAt: today, daysOnMarket: 9,
  },
  {
    id: '27', booliId: 100027, address: 'Hammarby Allé 45', area: 'Hammarby Sjöstad', municipality: 'Stockholm',
    price: 4_600_000, pricePerSqm: 76_667, livingArea: 60, rooms: 2, floor: 3, totalFloors: 7,
    constructionYear: 2003, monthlyFee: 3_100, propertyType: 'apartment',
    coordinates: { latitude: 59.3040, longitude: 18.0970 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Modern apartment in eco-friendly Hammarby Sjöstad.',
    url: 'https://www.booli.se/annons/100027', publishedAt: today, daysOnMarket: 3,
  },
  {
    id: '28', booliId: 100028, address: 'Solnavägen 10', area: 'Solna', municipality: 'Solna',
    price: 3_400_000, pricePerSqm: 68_000, livingArea: 50, rooms: 2, floor: 5, totalFloors: 8,
    constructionYear: 1970, monthlyFee: 2_500, propertyType: 'apartment',
    coordinates: { latitude: 59.3610, longitude: 18.0010 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Affordable apartment in Solna with good transport links.',
    url: 'https://www.booli.se/annons/100028', publishedAt: today, daysOnMarket: 22,
  },
  // Uppsala
  {
    id: '29', booliId: 100029, address: 'Svartbäcksgatan 14', area: 'Centrum', municipality: 'Uppsala',
    price: 2_800_000, pricePerSqm: 56_000, livingArea: 50, rooms: 2, floor: 2, totalFloors: 4,
    constructionYear: 1950, monthlyFee: 2_600, propertyType: 'apartment',
    coordinates: { latitude: 59.8590, longitude: 17.6340 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Central Uppsala apartment near the cathedral.',
    url: 'https://www.booli.se/annons/100029', publishedAt: today, daysOnMarket: 8,
  },
  {
    id: '30', booliId: 100030, address: 'Luthagen 25', area: 'Luthagen', municipality: 'Uppsala',
    price: 3_950_000, pricePerSqm: 56_429, livingArea: 70, rooms: 3, floor: 1, totalFloors: 3,
    constructionYear: 1925, monthlyFee: 3_200, propertyType: 'apartment',
    coordinates: { latitude: 59.8630, longitude: 17.6240 },
    images: [{ url: '/placeholder-apartment.jpg' }],
    description: 'Charming three-room in popular Luthagen neighborhood.',
    url: 'https://www.booli.se/annons/100030', publishedAt: today, daysOnMarket: 12,
  },
]
